version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cat_store
  cat-store:
    container_name: CatStore
    image: cat-store:0.0.1
    ports:
      - "8080:8080"
